# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "NFS-Server"
  config.vm.hostname = "NFS-Server"
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.10.10"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "NFS-Server"
	vb.gui = false
	vb.memory = "2048"
	vb.customize ["modifyvm", :id, "--audio", "none"]
  end
  #config.vm.provision "shell", inline: <<-SHELL
  #SHELL
  config.vm.provision "shell", path: "nfs_setup.sh"
end  
	