# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "k8master" do |k8master|
    k8master.vm.box = "centos/7"
    k8master.vm.hostname = "k8master.passion4learn.com"
    k8master.vm.network "private_network", ip: "192.168.10.100"
    k8master.vm.provider "virtualbox" do |v|
      v.name = "k8master"
      v.memory = 2048
      v.cpus = 2
      # Prevent VirtualBox from interfering with host audio stack
      v.customize ["modifyvm", :id, "--audio", "none"]
    end
    k8master.vm.provision "shell", path: "bootstrap_k8master.sh"
  end

  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "k8worker#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "k8worker#{i}.example.com"
      workernode.vm.network "private_network", ip: "192.168.10.10#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "k8worker#{i}"
        v.memory = 2048
        v.cpus = 2
        # Prevent VirtualBox from interfering with host audio stack
        v.customize ["modifyvm", :id, "--audio", "none"]
      end
      workernode.vm.provision "shell", path: "bootstrap_kworker.sh"
    end
  end

end
